// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: test.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message with enum
type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_PENDING   Status = 1
	Status_ACTIVE    Status = 2
	Status_COMPLETED Status = 3
	Status_FAILED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "ACTIVE",
		3: "COMPLETED",
		4: "FAILED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"ACTIVE":    2,
		"COMPLETED": 3,
		"FAILED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// Simple message with basic field types
type SimpleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Message with various numeric types
type NumericMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Field    int32                  `protobuf:"varint,1,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64                  `protobuf:"varint,2,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32                 `protobuf:"varint,3,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64                 `protobuf:"varint,4,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32                  `protobuf:"zigzag32,5,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64                  `protobuf:"zigzag64,6,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32                 `protobuf:"fixed32,7,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64                 `protobuf:"fixed64,8,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32                  `protobuf:"fixed32,9,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64                  `protobuf:"fixed64,10,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	FloatField    float32                `protobuf:"fixed32,11,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	DoubleField   float64                `protobuf:"fixed64,12,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericMessage) Reset() {
	*x = NumericMessage{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericMessage) ProtoMessage() {}

func (x *NumericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericMessage.ProtoReflect.Descriptor instead.
func (*NumericMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *NumericMessage) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *NumericMessage) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *NumericMessage) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *NumericMessage) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *NumericMessage) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *NumericMessage) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *NumericMessage) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *NumericMessage) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *NumericMessage) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *NumericMessage) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *NumericMessage) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *NumericMessage) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

// Message with repeated fields
type RepeatedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Words         []string               `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	Flags         []bool                 `protobuf:"varint,3,rep,packed,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedMessage) Reset() {
	*x = RepeatedMessage{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedMessage) ProtoMessage() {}

func (x *RepeatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedMessage.ProtoReflect.Descriptor instead.
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedMessage) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *RepeatedMessage) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *RepeatedMessage) GetFlags() []bool {
	if x != nil {
		return x.Flags
	}
	return nil
}

// Nested message structure
type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *NestedMessage_Inner   `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	InnerList     []*NestedMessage_Inner `protobuf:"bytes,2,rep,name=inner_list,json=innerList,proto3" json:"inner_list,omitempty"`
	OuterField    string                 `protobuf:"bytes,3,opt,name=outer_field,json=outerField,proto3" json:"outer_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *NestedMessage) GetInner() *NestedMessage_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *NestedMessage) GetInnerList() []*NestedMessage_Inner {
	if x != nil {
		return x.InnerList
	}
	return nil
}

func (x *NestedMessage) GetOuterField() string {
	if x != nil {
		return x.OuterField
	}
	return ""
}

// Deeply nested structure
type DeepNesting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level1        *DeepNesting_Level1    `protobuf:"bytes,1,opt,name=level1,proto3" json:"level1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting) Reset() {
	*x = DeepNesting{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting) ProtoMessage() {}

func (x *DeepNesting) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting.ProtoReflect.Descriptor instead.
func (*DeepNesting) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *DeepNesting) GetLevel1() *DeepNesting_Level1 {
	if x != nil {
		return x.Level1
	}
	return nil
}

type MessageWithEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithEnum) Reset() {
	*x = MessageWithEnum{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithEnum) ProtoMessage() {}

func (x *MessageWithEnum) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithEnum.ProtoReflect.Descriptor instead.
func (*MessageWithEnum) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *MessageWithEnum) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *MessageWithEnum) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Message with oneof
type MessageWithOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MessageWithOneof_StringValue
	//	*MessageWithOneof_IntValue
	//	*MessageWithOneof_BoolValue
	Value         isMessageWithOneof_Value `protobuf_oneof:"value"`
	CommonField   string                   `protobuf:"bytes,4,opt,name=common_field,json=commonField,proto3" json:"common_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithOneof) Reset() {
	*x = MessageWithOneof{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithOneof) ProtoMessage() {}

func (x *MessageWithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithOneof.ProtoReflect.Descriptor instead.
func (*MessageWithOneof) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *MessageWithOneof) GetValue() isMessageWithOneof_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageWithOneof) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneof_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MessageWithOneof) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneof_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MessageWithOneof) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneof_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MessageWithOneof) GetCommonField() string {
	if x != nil {
		return x.CommonField
	}
	return ""
}

type isMessageWithOneof_Value interface {
	isMessageWithOneof_Value()
}

type MessageWithOneof_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MessageWithOneof_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MessageWithOneof_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*MessageWithOneof_StringValue) isMessageWithOneof_Value() {}

func (*MessageWithOneof_IntValue) isMessageWithOneof_Value() {}

func (*MessageWithOneof_BoolValue) isMessageWithOneof_Value() {}

// Message with bytes
type MessageWithBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithBytes) Reset() {
	*x = MessageWithBytes{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithBytes) ProtoMessage() {}

func (x *MessageWithBytes) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithBytes.ProtoReflect.Descriptor instead.
func (*MessageWithBytes) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *MessageWithBytes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MessageWithBytes) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Message with map (represented as repeated in proto3)
type MessageWithMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int32       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Lookup        map[int32]string       `protobuf:"bytes,2,rep,name=lookup,proto3" json:"lookup,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithMap) Reset() {
	*x = MessageWithMap{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithMap) ProtoMessage() {}

func (x *MessageWithMap) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithMap.ProtoReflect.Descriptor instead.
func (*MessageWithMap) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *MessageWithMap) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *MessageWithMap) GetLookup() map[int32]string {
	if x != nil {
		return x.Lookup
	}
	return nil
}

// Complex real-world-like message
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AccountStatus Status                 `protobuf:"varint,7,opt,name=account_status,json=accountStatus,proto3,enum=testdata.Status" json:"account_status,omitempty"`
	Address       *UserProfile_Address   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *UserProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UserProfile) GetAccountStatus() Status {
	if x != nil {
		return x.AccountStatus
	}
	return Status_UNKNOWN
}

func (x *UserProfile) GetAddress() *UserProfile_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserProfile) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Empty message
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

type NestedMessage_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage_Inner) Reset() {
	*x = NestedMessage_Inner{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage_Inner) ProtoMessage() {}

func (x *NestedMessage_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage_Inner.ProtoReflect.Descriptor instead.
func (*NestedMessage_Inner) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3, 0}
}

func (x *NestedMessage_Inner) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NestedMessage_Inner) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeepNesting_Level1 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Level2        *DeepNesting_Level1_Level2 `protobuf:"bytes,1,opt,name=level2,proto3" json:"level2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting_Level1) Reset() {
	*x = DeepNesting_Level1{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting_Level1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting_Level1) ProtoMessage() {}

func (x *DeepNesting_Level1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting_Level1.ProtoReflect.Descriptor instead.
func (*DeepNesting_Level1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DeepNesting_Level1) GetLevel2() *DeepNesting_Level1_Level2 {
	if x != nil {
		return x.Level2
	}
	return nil
}

type DeepNesting_Level1_Level2 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Level3        *DeepNesting_Level1_Level2_Level3 `protobuf:"bytes,1,opt,name=level3,proto3" json:"level3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting_Level1_Level2) Reset() {
	*x = DeepNesting_Level1_Level2{}
	mi := &file_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting_Level1_Level2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting_Level1_Level2) ProtoMessage() {}

func (x *DeepNesting_Level1_Level2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting_Level1_Level2.ProtoReflect.Descriptor instead.
func (*DeepNesting_Level1_Level2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *DeepNesting_Level1_Level2) GetLevel3() *DeepNesting_Level1_Level2_Level3 {
	if x != nil {
		return x.Level3
	}
	return nil
}

type DeepNesting_Level1_Level2_Level3 struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Level4        *DeepNesting_Level1_Level2_Level3_Level4 `protobuf:"bytes,1,opt,name=level4,proto3" json:"level4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting_Level1_Level2_Level3) Reset() {
	*x = DeepNesting_Level1_Level2_Level3{}
	mi := &file_test_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting_Level1_Level2_Level3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting_Level1_Level2_Level3) ProtoMessage() {}

func (x *DeepNesting_Level1_Level2_Level3) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting_Level1_Level2_Level3.ProtoReflect.Descriptor instead.
func (*DeepNesting_Level1_Level2_Level3) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0, 0, 0}
}

func (x *DeepNesting_Level1_Level2_Level3) GetLevel4() *DeepNesting_Level1_Level2_Level3_Level4 {
	if x != nil {
		return x.Level4
	}
	return nil
}

type DeepNesting_Level1_Level2_Level3_Level4 struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Level5        *DeepNesting_Level1_Level2_Level3_Level4_Level5 `protobuf:"bytes,1,opt,name=level5,proto3" json:"level5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting_Level1_Level2_Level3_Level4) Reset() {
	*x = DeepNesting_Level1_Level2_Level3_Level4{}
	mi := &file_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting_Level1_Level2_Level3_Level4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting_Level1_Level2_Level3_Level4) ProtoMessage() {}

func (x *DeepNesting_Level1_Level2_Level3_Level4) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting_Level1_Level2_Level3_Level4.ProtoReflect.Descriptor instead.
func (*DeepNesting_Level1_Level2_Level3_Level4) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0, 0, 0, 0}
}

func (x *DeepNesting_Level1_Level2_Level3_Level4) GetLevel5() *DeepNesting_Level1_Level2_Level3_Level4_Level5 {
	if x != nil {
		return x.Level5
	}
	return nil
}

type DeepNesting_Level1_Level2_Level3_Level4_Level5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeepValue     string                 `protobuf:"bytes,1,opt,name=deep_value,json=deepValue,proto3" json:"deep_value,omitempty"`
	DeepNumber    int32                  `protobuf:"varint,2,opt,name=deep_number,json=deepNumber,proto3" json:"deep_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNesting_Level1_Level2_Level3_Level4_Level5) Reset() {
	*x = DeepNesting_Level1_Level2_Level3_Level4_Level5{}
	mi := &file_test_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNesting_Level1_Level2_Level3_Level4_Level5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNesting_Level1_Level2_Level3_Level4_Level5) ProtoMessage() {}

func (x *DeepNesting_Level1_Level2_Level3_Level4_Level5) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNesting_Level1_Level2_Level3_Level4_Level5.ProtoReflect.Descriptor instead.
func (*DeepNesting_Level1_Level2_Level3_Level4_Level5) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0, 0, 0, 0, 0}
}

func (x *DeepNesting_Level1_Level2_Level3_Level4_Level5) GetDeepValue() string {
	if x != nil {
		return x.DeepValue
	}
	return ""
}

func (x *DeepNesting_Level1_Level2_Level3_Level4_Level5) GetDeepNumber() int32 {
	if x != nil {
		return x.DeepNumber
	}
	return 0
}

type UserProfile_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile_Address) Reset() {
	*x = UserProfile_Address{}
	mi := &file_test_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile_Address) ProtoMessage() {}

func (x *UserProfile_Address) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile_Address.ProtoReflect.Descriptor instead.
func (*UserProfile_Address) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UserProfile_Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UserProfile_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserProfile_Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UserProfile_Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *UserProfile_Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\btestdata\"K\n" +
	"\rSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\xba\x03\n" +
	"\x0eNumericMessage\x12\x1f\n" +
	"\vint32_field\x18\x01 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x02 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x03 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x04 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\x05 \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\x06 \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\a \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\b \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\t \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\n" +
	" \x01(\x10R\rsfixed64Field\x12\x1f\n" +
	"\vfloat_field\x18\v \x01(\x02R\n" +
	"floatField\x12!\n" +
	"\fdouble_field\x18\f \x01(\x01R\vdoubleField\"W\n" +
	"\x0fRepeatedMessage\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\x12\x14\n" +
	"\x05words\x18\x02 \x03(\tR\x05words\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\bR\x05flags\"\xd8\x01\n" +
	"\rNestedMessage\x123\n" +
	"\x05inner\x18\x01 \x01(\v2\x1d.testdata.NestedMessage.InnerR\x05inner\x12<\n" +
	"\n" +
	"inner_list\x18\x02 \x03(\v2\x1d.testdata.NestedMessage.InnerR\tinnerList\x12\x1f\n" +
	"\vouter_field\x18\x03 \x01(\tR\n" +
	"outerField\x1a3\n" +
	"\x05Inner\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xd7\x03\n" +
	"\vDeepNesting\x124\n" +
	"\x06level1\x18\x01 \x01(\v2\x1c.testdata.DeepNesting.Level1R\x06level1\x1a\x91\x03\n" +
	"\x06Level1\x12;\n" +
	"\x06level2\x18\x01 \x01(\v2#.testdata.DeepNesting.Level1.Level2R\x06level2\x1a\xc9\x02\n" +
	"\x06Level2\x12B\n" +
	"\x06level3\x18\x01 \x01(\v2*.testdata.DeepNesting.Level1.Level2.Level3R\x06level3\x1a\xfa\x01\n" +
	"\x06Level3\x12I\n" +
	"\x06level4\x18\x01 \x01(\v21.testdata.DeepNesting.Level1.Level2.Level3.Level4R\x06level4\x1a\xa4\x01\n" +
	"\x06Level4\x12P\n" +
	"\x06level5\x18\x01 \x01(\v28.testdata.DeepNesting.Level1.Level2.Level3.Level4.Level5R\x06level5\x1aH\n" +
	"\x06Level5\x12\x1d\n" +
	"\n" +
	"deep_value\x18\x01 \x01(\tR\tdeepValue\x12\x1f\n" +
	"\vdeep_number\x18\x02 \x01(\x05R\n" +
	"deepNumber\"]\n" +
	"\x0fMessageWithEnum\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.testdata.StatusR\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xa3\x01\n" +
	"\x10MessageWithOneof\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\fcommon_field\x18\x04 \x01(\tR\vcommonFieldB\a\n" +
	"\x05value\"<\n" +
	"\x10MessageWithBytes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x82\x02\n" +
	"\x0eMessageWithMap\x12<\n" +
	"\x06counts\x18\x01 \x03(\v2$.testdata.MessageWithMap.CountsEntryR\x06counts\x12<\n" +
	"\x06lookup\x18\x02 \x03(\v2$.testdata.MessageWithMap.LookupEntryR\x06lookup\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a9\n" +
	"\vLookupEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x04\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x127\n" +
	"\x0eaccount_status\x18\a \x01(\x0e2\x10.testdata.StatusR\raccountStatus\x127\n" +
	"\aaddress\x18\b \x01(\v2\x1d.testdata.UserProfile.AddressR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12?\n" +
	"\bmetadata\x18\v \x03(\v2#.testdata.UserProfile.MetadataEntryR\bmetadata\x1aw\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x04 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fEmptyMessage*I\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B<Z:github.com/egonelbre/protobuf-compression/pbmodel/testdatab\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_test_proto_goTypes = []any{
	(Status)(0),                                            // 0: testdata.Status
	(*SimpleMessage)(nil),                                  // 1: testdata.SimpleMessage
	(*NumericMessage)(nil),                                 // 2: testdata.NumericMessage
	(*RepeatedMessage)(nil),                                // 3: testdata.RepeatedMessage
	(*NestedMessage)(nil),                                  // 4: testdata.NestedMessage
	(*DeepNesting)(nil),                                    // 5: testdata.DeepNesting
	(*MessageWithEnum)(nil),                                // 6: testdata.MessageWithEnum
	(*MessageWithOneof)(nil),                               // 7: testdata.MessageWithOneof
	(*MessageWithBytes)(nil),                               // 8: testdata.MessageWithBytes
	(*MessageWithMap)(nil),                                 // 9: testdata.MessageWithMap
	(*UserProfile)(nil),                                    // 10: testdata.UserProfile
	(*EmptyMessage)(nil),                                   // 11: testdata.EmptyMessage
	(*NestedMessage_Inner)(nil),                            // 12: testdata.NestedMessage.Inner
	(*DeepNesting_Level1)(nil),                             // 13: testdata.DeepNesting.Level1
	(*DeepNesting_Level1_Level2)(nil),                      // 14: testdata.DeepNesting.Level1.Level2
	(*DeepNesting_Level1_Level2_Level3)(nil),               // 15: testdata.DeepNesting.Level1.Level2.Level3
	(*DeepNesting_Level1_Level2_Level3_Level4)(nil),        // 16: testdata.DeepNesting.Level1.Level2.Level3.Level4
	(*DeepNesting_Level1_Level2_Level3_Level4_Level5)(nil), // 17: testdata.DeepNesting.Level1.Level2.Level3.Level4.Level5
	nil,                         // 18: testdata.MessageWithMap.CountsEntry
	nil,                         // 19: testdata.MessageWithMap.LookupEntry
	(*UserProfile_Address)(nil), // 20: testdata.UserProfile.Address
	nil,                         // 21: testdata.UserProfile.MetadataEntry
}
var file_test_proto_depIdxs = []int32{
	12, // 0: testdata.NestedMessage.inner:type_name -> testdata.NestedMessage.Inner
	12, // 1: testdata.NestedMessage.inner_list:type_name -> testdata.NestedMessage.Inner
	13, // 2: testdata.DeepNesting.level1:type_name -> testdata.DeepNesting.Level1
	0,  // 3: testdata.MessageWithEnum.status:type_name -> testdata.Status
	18, // 4: testdata.MessageWithMap.counts:type_name -> testdata.MessageWithMap.CountsEntry
	19, // 5: testdata.MessageWithMap.lookup:type_name -> testdata.MessageWithMap.LookupEntry
	0,  // 6: testdata.UserProfile.account_status:type_name -> testdata.Status
	20, // 7: testdata.UserProfile.address:type_name -> testdata.UserProfile.Address
	21, // 8: testdata.UserProfile.metadata:type_name -> testdata.UserProfile.MetadataEntry
	14, // 9: testdata.DeepNesting.Level1.level2:type_name -> testdata.DeepNesting.Level1.Level2
	15, // 10: testdata.DeepNesting.Level1.Level2.level3:type_name -> testdata.DeepNesting.Level1.Level2.Level3
	16, // 11: testdata.DeepNesting.Level1.Level2.Level3.level4:type_name -> testdata.DeepNesting.Level1.Level2.Level3.Level4
	17, // 12: testdata.DeepNesting.Level1.Level2.Level3.Level4.level5:type_name -> testdata.DeepNesting.Level1.Level2.Level3.Level4.Level5
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[6].OneofWrappers = []any{
		(*MessageWithOneof_StringValue)(nil),
		(*MessageWithOneof_IntValue)(nil),
		(*MessageWithOneof_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
